name: Setup
runs:
  using: composite
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - uses: jetli/wasm-pack-action@v0.4.0
    - name: Build Rust Analyzer
      run: ./setup-wasm.sh
      shell: bash
    - name: Install Graco
      run: npm install -g graco
      shell: bash
    - name: Build frontend
      run: graco init && graco build
      shell: bash
