name: Tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
        
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - run: npm install -g graco
      - run: graco build